### ISSUE TITLE
intercept with metric predictors

### ISSUE THREAD

**Issue by SanVerhavert** [richarddmorey/BayesFactor#101]
Is there a reason why `posterior` does not return samples for the intercept (or mu) when metric predictors are used?

**Comment by richarddmorey** [comment]
Yes; it was integrated out analytically, and so does not appear in the Gibbs sampler output.  This will change in the next version of BayesFactor. See https://github.com/richarddmorey/BayesFactor/commit/12829f1c29d1796140a41e59e6fdf18755187de3
