### ISSUE TITLE
Non-point null hypothesis testing with lmBF() 

### ISSUE THREAD

**Issue by cvonbastian** [richarddmorey/BayesFactor#109]
Hi Richard, 

I'm currently running a couple of linear models with lmBF() and was wondering whether there's an equivalent to setting nullInterval=c(-Inf,0) in ttestBF(). I was thinking to do something along the lines of comparing an H1 model in which the prior for a particular factor is set to a positive half-Cauchy to an H0 model where the prior for the same factor is set to a negative interval, but couldn't figure out a way to set custom priors for the lmBF(). 

Any pointers would be greatly appreciated! 

Many thanks and best,
Claudia

**Comment by richarddmorey** [comment]
Hi Claudia,

You can do this: http://bayesfactor.blogspot.co.uk/2015/01/multiple-comparisons-with-bayesfactor-2.html

I believe Candice Morey has used this in a paper; you might want to ask her for details on how she reported it.

Best,
Richard

**Comment by cvonbastian** [comment]
Thanks so much, Richard, that's exactly the kind of thing that I was looking for! 
I'll get in touch with Candice regarding her paper, too!

Best,
Claudia
