### ISSUE TITLE
Negative BF value

### ISSUE THREAD

**Issue by staplesc** [richarddmorey/BayesFactor#110]
I'm using anovaBF, but occasionally get a negative Bayes factor. I'm a beginner in R, and not a statistics whiz (clearly!) Any suggestions on what I might be doing wrong?

I'm using R3.4.1. The BayesFactor package is version 0.9.12-2.

Thanks in advance for your help.

**Comment by richarddmorey** [comment]
Can you provide some reproducible code?

**Comment by richarddmorey** [comment]
No, that's the logarithm of the Bayes factor. Try

```
set.seed(123)
bf <- BayesFactor::ttestBF(x=rnorm(31, 0.54, 0.22), mu=0.5)
as.vector(bf)
```

**Comment by DominiqueMakowski** [comment]
thanks a lot :)
