### ISSUE TITLE
mixed effect logistic regression?

### ISSUE THREAD

**Issue by superdayv** [richarddmorey/BayesFactor#115]
Hi There

I'm wondering if this package can handle mixed effects logistic regressions? By mixed effects I mean a model with random subject and item terms. Thank you!

Dave

**Comment by superdayv** [comment]
I should actually ask if it is possible to specify more than one random effect? E.g., if analyzing trial level data consisting of multiple items, observed in multiple subjects.

**Comment by richarddmorey** [comment]
No, not yet, unfortunately.
