### ISSUE TITLE
meta.ttestBF 't is large; approximation invoked'

### ISSUE THREAD

**Issue by metalguruisityou** [richarddmorey/BayesFactor#117]
I've used the meta.ttestBF function to t-statistics from two different experiments, with different sample sizes, and different results. Before providing me with the Bayes factor analysis I get a message saying 't is large; approximation invoked'. 

I've done a search but can't find out what exactly is approximated and how this might affect the analysis. 

I noticed that where the standard error of the BF is usually it says 'NA'. 

The documentation doesn't mention anything about this so it would be great if you could clarify.

**Comment by richarddmorey** [comment]
When t is very large, the typical gaussian quadrature will fail and so BayesFactor uses a t(df) approximation to the posterior. You can find the approximation here: https://github.com/richarddmorey/BayesFactor/blob/6e69b0b0694671ca9b7b46fae54cfecd6ec587df/pkg/BayesFactor/R/meta-ttest-utility.R#L203
