### ISSUE TITLE
Bayesian t-test for large samples

### ISSUE THREAD

**Issue by DominiqueMakowski** [richarddmorey/BayesFactor#118]
I am trying to compare large normal distributions (n > 1000) to mu = 0. However, the bayes factor becomes quickly very large (or infinite), even though visually the distribution is relatively close to 0 (a large proportion of it overlaps 0 and the opposite side).

```r
set.seed(123)
p <- rnorm(4000, -0.3, 0.50)
plot(density(p))
BayesFactor::ttestBF(p)
```
![image](https://user-images.githubusercontent.com/8875533/39308970-2ad3a774-4967-11e8-8f34-c01c7dc85b58.png)

Is there any less sensitive alternatives? That would require larger deviations to consider evidence for alternative hypothesis?

Thanks

**Comment by richarddmorey** [comment]
I'm not sure what you mean; the Bayes factor is as sensitive as the method should be. For what it's worth, the p value is at the limit of numerical precision as well (<2.2e-16).

**Comment by DominiqueMakowski** [comment]
Alright it was the question that I asked that was wrong. Thanks for your answer :)
