### ISSUE TITLE
anovaBF() docs should reference extractBF()

### ISSUE THREAD

**Issue by earcanal** [richarddmorey/BayesFactor#124]
I _think_ you need `extractBF()` to extract BFs from `anovaBF()`? This isn't clear from the `anovaBF()` docs.

**Comment by richarddmorey** [comment]
You don't _need_ `extractBF()`; `as.vector()` or `as.data.frame()` will also do it.

**Comment by richarddmorey** [comment]
Sure, if you want to make a pull request I'll merge it.
