### ISSUE TITLE
feature request: adding support for Welch's t-test

### ISSUE THREAD

**Issue by IndrajeetPatil** [richarddmorey/BayesFactor#136]
If I am not mistaken, currently only the Student's _t_-test assuming equal variances is supported? 

If yes, it will also be nice to add support for Welch's _t_-test with an additional argument (e.g., `var.equal`) to `ttestBF`, which will be relevant for between-subjects designs.

**Comment by richarddmorey** [comment]
Welch's test is specifically designed to control Type I error rate (that is inherent in its design). How would that be incorporated into the BayesFactor test?
