### ISSUE TITLE
tests failing in daily CRAN checks 

### ISSUE THREAD

**Issue by IndrajeetPatil** [richarddmorey/BayesFactor#145]
Maybe you have already received an e-mail from `CRAN`, but just in case you haven't:
https://cran.r-project.org/web/checks/check_results_BayesFactor.html

![image](https://user-images.githubusercontent.com/11330453/91960328-1110f000-ed0a-11ea-9a64-cd53c4e904dc.png)

I noticed it because I couldn't submit revision of my own package due to these failing tests.

**Comment by richarddmorey** [comment]
Thanks; I had seen this. Not sure what could be causing it yet.

**Comment by IndrajeetPatil** [comment]
Hmm, maybe there is nothing wrong to begin with and this was a temporary snag introduced by some changes in R-devel?

<img width="598" alt="Screenshot 2020-09-06 at 13 01 25" src="https://user-images.githubusercontent.com/11330453/92324347-299e4480-f041-11ea-8dad-ab6f59584b60.png">

**Comment by IndrajeetPatil** [comment]
I will keep this open until this is fully resolved since now the tests are failing on Windows machine:

https://cran.r-project.org/web/checks/check_results_BayesFactor.html

**Comment by richarddmorey** [comment]
When I checked earlier today everything had resolved itself. I wonder what's going on over there?

**Comment by richarddmorey** [comment]
All the errors have disappeared now. Let's give it a day and close this up if things stay that way.
