### ISSUE TITLE
Changing the location hyperparameter for the rscale in ttestBF

### ISSUE THREAD

**Issue by mz555** [richarddmorey/BayesFactor#157]
In JASP, when conducting a t-test you have the option to use informed priors for Cauchy, such as changing the r-scale and location.
In `ttestBF` I can change the r-scale, but I don't seem to be able to add a location argument. Is it possible to do so? 

For context, I see frequentist misrepresenting the r-scale as equivalent to cohen's d, such that if in the study you are replicating the original d = .42, they set the prior as r-scale = .42; but this is not the same, as the r-scale is a distribution of values with mode = 0. Someone suggested as a solution to use r-scale = .01, and location = .42. I can do so in JASP, but I would like to be able to do this in R. (note, I tried nullInterval = c(.41, 43), but the results were not comparable to JASP).

Any help is appreciated.

**Comment by richarddmorey** [comment]
This is not possible using the default prior setup in BayesFactor. If you'd like to compute a BayesFactor for any prior you can think of (including adding a location) you can see this code: https://gist.github.com/richarddmorey/3dbd911466389f7f263e
