### ISSUE TITLE
lmBF (and other functions with random factors?) always throws an error

### ISSUE THREAD

**Issue by atkin165** [richarddmorey/BayesFactor#163]
I've just returned to some old code for paper revisions, and my previously working lmBF models now will no longer run. Every time, I get the following error: "Error in if (...length() && any(...names() == "Dimnames")) .Object@Dimnames <- fixupDN(.Object@Dimnames) : missing value where TRUE/FALSE needed."

This seems to be a package-wide problem, as even the example code from the documentation does not work. I've tried both of the following and received the same error as above.
bf = anovaBF(RT ~ shape*color + ID, data= puzzles, whichRandom = "ID")
bfFull = lmBF(RT ~ shape + color + shape:color + ID, data = puzzles, whichRandom = "ID")

**Comment by mwarb** [comment]
@atkin165 Did you find a solution to this? I have the same issue, which seems to have happened after updating the Matrix package to the latest version.

**Comment by richarddmorey** [comment]
Can you provide a reproducible example with a session info and maybe an renv.lock file?
