### ISSUE TITLE
A huge difference of BF of ttest between ttestBF and JASP

### ISSUE THREAD

**Issue by AaronZheng87** [richarddmorey/BayesFactor#170]
Dear developers
I found there are different results when I use BayesFactor::ttestBF and JASP to calculate BF10 value based on independent t test. But the result from JASP met the result from BayesFactor::lmBF, I am wondering why?

Looking forward to your reply!
<img width="1076" alt="9bo2KGCTuk" src="https://github.com/richarddmorey/BayesFactor/assets/74256146/c4c33e3f-ce12-4145-a928-c35672ec5c48">
<img width="723" alt="al7heqe2cp" src="https://github.com/richarddmorey/BayesFactor/assets/74256146/a4b49d89-e319-4689-bdad-a1fa3674e6db">
<img width="528" alt="6u4Q6awOmI" src="https://github.com/richarddmorey/BayesFactor/assets/74256146/8a0b9319-d43f-44b6-8315-a3c967ccb49b">

**Comment by richarddmorey** [comment]
Without your data and code, it is impossible to say what's going on (or even to understand your analysis) but I see in your JASP analysis a BF of 21.332, and in your BayesFactor analysis a BF of 21.33138. Are these the BFs you're saying are different?

**Comment by AaronZheng87** [comment]
Dear developer

I used the ttestBF function and the result is 8.612346e+89 ±0%:
```
ttestBF(y = dat$BEH, x = dat$PRIME, paired=FALSE,rscale=sqrt(2)/2)
```
it is different This is different from the result of jasp: 21.332.
But the result of JASP is similar to the result of lmBF:21.33138

The whole code is: 
```
rm(list=ls())
library(pacman)
p_load(tidyverse, BayesFactor, foreign)
dat <- read_csv('data.csv')
dat %>% 
  glimpse()
dat$PRIME <- factor(dat$PRIME)
ttestBF(y = dat$BEH, x = dat$PRIME, paired=FALSE,rscale=sqrt(2)/2)

```
[data.csv](https://github.com/richarddmorey/BayesFactor/files/13927983/data.csv)

Thank you for your reply, and l am looking forward to hearing from you.

**Comment by richarddmorey** [comment]
Could you provide me with the code you used to get the lmBF result?

**Comment by AaronZheng87** [comment]
Dear developer 
here is my code and screenshot:
```
lmBF(BEH ~ PRIME, data = dat)
```
<img width="1440" alt="截屏2024-01-15 10 07 52" src="https://github.com/richarddmorey/BayesFactor/assets/74256146/b430832c-4c39-4b0f-8146-8e72c6a44dbd">

**Comment by richarddmorey** [comment]
From your lmBF analysis, it appears that `PRIME` is a grouping variable? If so, your ttestBF syntax is wrong. You're comparing your DV to the the grouping variable. See the [BayesFactor manual](https://cran.r-project.org/web/packages/BayesFactor/vignettes/manual.html#twosample) for the syntax you want.
