### ISSUE TITLE
Error in if (...length() && any(...names() == "Dimnames")) .Object@Dimnames <- fixupDN(.Object@Dimnames) :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by connorspiech** [richarddmorey/BayesFactor#172]
anovaBF throws this error on my machine running Pop! OS 22.04 with R 4.1.2 in RStudio 2023.12.1 Build 402: 

Error in if (...length() && any(...names() == "Dimnames")) .Object@Dimnames <- fixupDN(.Object@Dimnames) : missing value where TRUE/FALSE needed

I found someone who ran into the same problem on Stack Exchange who said that fresh reinstalls of R and RStudio did the trick for him but it hasn't worked for me. I saw that someone else here experienced this same problem (including reinstalling not helping) and they appeared to be running Linux as well but the issue was closed. Is there any plan to fix this? It's wicked annoying having to send my data and code to my colleague to run on his Macbook.

**Comment by richarddmorey** [comment]
I don't think this has anything to do with BayesFactor. Certainly the code that triggered the error (involving "fixupDN()") isn't BayesFactor code, and the Stack Exchange comments suggest it is an R issue, not BayesFactor, so I don't think I can do anything for you (unless you can send me a reproducible example).

Have you tried upgrading R?
