### ISSUE TITLE
What is the g parameter in ttestBF for? 

### ISSUE THREAD

**Issue by crowston** [richarddmorey/BayesFactor#174]
Sorry if this is not the right place to ask this question, in which case, please redirect me. I am trying to understand the output for a two-factor Bayesian t-test using ttestBF in the BayesFactor R library. E.g., 

```
summarise_draws(ttestBF(formula=mpg ~ am, data=mtcars, posterior = TRUE, iterations=10000))

# A tibble: 5 × 10
  variable      mean median      sd   mad     q5    q95  rhat ess_bulk ess_tail
  <chr>        <dbl>  <dbl>   <dbl> <dbl>  <dbl>  <dbl> <dbl>    <dbl>    <dbl>
1 mu           20.7   20.7    0.906 0.897 19.3   22.2    1.00    9154.    9445.
2 beta (0 - 1) -6.47  -6.50   1.90  1.89  -9.54  -3.33   1.00    6325.    7587.
3 sig2         26.2   25.0    7.18  6.35  16.8   39.4    1.00    8040.    8876.
4 delta        -1.30  -1.30   0.418 0.418 -1.99  -0.618  1.00    6047.    7374.
5 g            14.0    1.60 444.    1.59   0.291 22.6    1.00    6968.    8035.
```

There's a mysterious parameter g that does not seem to be documented anywhere that I can find. It bounces around a lot, witness the high sd.

In the source code for the Gibbs sampler for the test [here][1], g is initialized to:

```
g = pow(beta, 2) / sig2 + 1
```

and makes an appearance in computing the variance for beta and the scale for sig2

```
varBeta  = sig2 / ( sumN/4 + 1/g );

scaleSig2 = 0.5 * ( sumySq - 2.0 * mu * sumy - beta * diffy +
                          N[0] * pow(mu - beta/2, 2) + N[1] * pow(mu + beta/2, 2) );
if(!nullModel) scaleSig2 += pow(beta, 2) / g / 2
```

g itself seems to be an inverse gamma:

```
scaleg = 0.5 * ( pow(beta,2) / sig2 + rscaleSq );
g = 1 / Rf_rgamma( 0.5 * (1 + !nullModel), 1/scaleg );
```

I thought the answer might have something to do with [this][2] question on Stack Exchange about the g in a JZS prior for a Bayesian t test, but I am not seeing the connection. 

Any insight into what it's doing in the model would be greatly welcomed. 

  [1]: https://github.com/cran/BayesFactor/blob/676d612e579ad93c2d86b00ac0e4d9f970e5feef/src/ttestIndepRcpp.cpp
  [2]: https://stats.stackexchange.com/questions/570605/understanding-the-jeffreys-zellner-siow-jzs-prior-in-bayesian-t-tests

**Comment by AbdullahSK03** [comment]
This might help:This file might fix it
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by richarddmorey** [comment]
I see you closed it - did you find your answer? It is, indeed, from the g prior. It is useful a variety of things that some people might care about so we include it. It is much more important in our models with random effects.

**Comment by crowston** [comment]
I closed the issue because I found the help forum and thought it would be more appropriate to ask there. Also the first response was a phishing attack, which I didn’t want hanging around, though I see you deleted it.

So, is this a correct interpretation?

g is a parameter in the priors that "can be interpreted as a measure of the amount of information available in the prior relative to the sample" [1]: "choosing a smaller value for g means that one has a stronger belief in this guess. Conversely, choosing larger values of g has an effect similar to choosing the noninformative prior" [2].

1. Jean-Michel Marin and Christian P. Robert. (2007). Regression and Variable Selection. In: Bayesian Core: A Practical Approach to Computational Bayesian Statistics. Springer Texts in Statistics. Springer, New York, NY. https://doi-org.libezproxy2.syr.edu/10.1007/978-0-387-38983-7_3

2. Miguel Trejo. (2020). "Linear Regression Model Selection through Zellner’s g prior". In Towards Data Science. Available from: https://towardsdatascience.com/linear-regression-model-selection-through-zellners-g-prior-da5f74635a03

Thanks!

**Comment by richarddmorey** [comment]
For the BF t test you can think of it as an integration gimmick, and it makes the tails on the prior for the effect very thick and allows the BF to approach infinity as t->infinity (we explain this in the 2009 Bayesian t test paper, I think).

**Comment by crowston** [comment]
Thanks.
