### ISSUE TITLE
Bad t-test citation in documentation

### ISSUE THREAD

**Issue by jonathon-love** [richarddmorey/BayesFactor#47]
in your t-test documentation you have:

`Rouder, J. N., Speckman, P. L., Sun, D., Morey, R. D., & Iverson, G. (2009). Bayesian t-tests for accepting and rejecting the null hypothesis. Psychonomic Bulletin & Review, 16, 752-760`

but i think you mean pages `225-237`

**Comment by richarddmorey** [comment]
Indeed, I wonder how that happened.
