### ISSUE TITLE
generalTestBF(): error with a particular analysis

### ISSUE THREAD

**Issue by jonathon-love** [richarddmorey/BayesFactor#51]
using BayesFactor 0.9.10-2

    x <- as.factor(1:10)
    y <- 1:10
    d <- data.frame(x, y)
    
    generalTestBF(y ~ x, d)

outputs

    >  |                                                                                                          |   0%
    > Error in `[.data.frame`(summary(aov(formula, data = data))[[1]], "F value") : 
    >   undefined columns selected

**Comment by richarddmorey** [comment]
Hmm, yes, that corresponds to a nonsense analysis. I can make that yield an error earlier on.
