### ISSUE TITLE
ttestBF: posterior sampling respecting mu parameter

### ISSUE THREAD

**Issue by quentingronau** [richarddmorey/BayesFactor#59]
Hi,

When sampling from the posterior via ttestBF, the mu parameter is not respected.

**Comment by richarddmorey** [comment]
This will be an easy fix for the next version of BayesFactor.

**Comment by quentingronau** [comment]
Great, thanks.

**Comment by richarddmorey** [comment]
What is it that you want to happen here? Now that I look at this, it appears to be doing what I would expect. ttestBF tests against a specific mu, but posterior ignores mu (because it isn't a test). Can you describe what you expect?

**Comment by quentingronau** [comment]
Hi Richard,

To be honest, I do not really remember what exactly the issue was. I think you are completely right, the function does what the user expects and I do not see an issue anymore. Sorry if I caused confusion, I think you can close this issue.

Cheers,
Quentin
