### ISSUE TITLE
ttest.tstat gives error with n > 46340

### ISSUE THREAD

**Issue by nicebread** [richarddmorey/BayesFactor#61]
While running a simulation, ttest.tstat gives an error when n > 46340 (because 46340^2 exceeds the integer range and produces an integer overflow).
Such sample sizes might be rare in reality, but maybe it would be nice if the function does not return an error but rather NA or NULL?

**Comment by richarddmorey** [comment]
hmmmm, yes; there also might be a way around the problem. I'll take a look. Can you provide a reproducible example just for my reference?

**Comment by nicebread** [comment]
Oops - very strange: I cannot reproduce the error any more.
I'm closing the issue. If I discover it again, I'll tell you.
