### ISSUE TITLE
Nonfactors are specified as random

### ISSUE THREAD

**Issue by js1551** [richarddmorey/BayesFactor#71]
bf = anovaBF(R~Condition*Handedness + Subject, whichRandom = "Subject", 
             data = master,
             whichModels = "withmain",
             iterations = 100000)

I'm trying to run this analysis, but I keep getting this error message:

Error in createDataTypes(formula, whichRandom, data, analysis = "anova") : 
  Nonfactors are specified as random.

Any suggestions??

**Comment by nicebread** [comment]
The column "Subject" in your data frame must be defined as a factor (I guess it's a numeric variable at the moment).

**Comment by richarddmorey** [comment]
Closing this up.
