### ISSUE TITLE
whichModels = "top" throws error for unifactorial models in anovaBF

### ISSUE THREAD

**Issue by crsh** [richarddmorey/BayesFactor#72]
Hi Richard,

I think I just ran into a minor bug.

~~~{r}
anovaBF(
  extra ~ group + ID
  , data = sleep
  , whichRandom = "ID"
  , whichModels = "top"
)
~~~

This throws the following error (translated from German):

> Error in tempfile(rep("", n), "", "") : no 'pattern' provided

It appears the calculations are being run (the progress bar reaches 100%) but something breaks while assembling the S4 object. The culprit is `whichModels = "top"`. Once I omit this it works. This also happens in unifactorial models without random effects.

~~~{r}
anovaBF(
  extra ~ group
  , data = sleep
  , whichModels = "top"
)
~~~

**Comment by richarddmorey** [comment]
Thanks! I'll check it out and correct it for the next version.
