### ISSUE TITLE
ttestBF: how to use the "nullInterval" argument to get BF for mean > some value on DV?

### ISSUE THREAD

**Issue by chsquare** [richarddmorey/BayesFactor#77]
Hi All!
I'm trying to figure out how to use the ttestBF function to get the BF for a one-sample test of something like mean > 3 (units on my dependent variable) versus mean <= 3. I think the "nullInterval" argument is the way to go, but in the docs it says the nullInterval should be specified in standardized units. What kind of standardization is done here? Is it correct to just scale the value "3" by the standard deviation of my sample?
I greatly appreciate any help. 
Thank you very much,
Christoph

**Comment by richarddmorey** [comment]
Because the prior is placed on the standardised effect and the prior on sigma^2 is improper, there is technically no such Bayes factor. I would recommend going with model that has proper priors placed on your parameters for your purposes; see a Bayesian textbook for details on how to do this.

**Comment by chsquare** [comment]
Thanks for the quick reply and the clue to the solution!
