### ISSUE TITLE
ttestbf: Error in is.infinite(c(x, y))

### ISSUE THREAD

**Issue by baranan** [richarddmorey/BayesFactor#78]
Using this code:
```
why <- data.frame(DV = c(5, 6, 7, 7, 8, 9), IV = c(1, 1, 1, 0, 0, 0))
ttestBF(DV ~ IV, data = why)
```
Shows me the error in my rstudio: 
Error in is.infinite(c(x, y)) : default method not implemented for type 'list'
In R-Fiddle it shows me this error:
Error : error in evaluating the argument 'data' in selecting a method for function 'compare': Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ""formula"" to a data.frame

I can't figure out from the error messages or from the documentation what I'm doing wrong.

**Comment by richarddmorey** [comment]
You're not passing the formula argument explicitly. Try this:

    BayesFactor::ttestBF(formula=DV ~ IV, data = why)

**Comment by baranan** [comment]
Yes, that works great with my example and with my actual data. Thank you very much.
