### ISSUE TITLE
Effect size ?

### ISSUE THREAD

**Issue by lnalborczyk** [richarddmorey/BayesFactor#93]
Hi,

first of all, let me thank you for the amazing work with `BayesFactor`.

Then, I would like to know if you have planned to implement the effect size computations detailed in [Marsman et al. (2017)](http://www.stat.columbia.edu/~gelman/research/published/birdseye.pdf) ? 

It would be great (IMO) if `ttestBF` (for instance) could output an effect size estimate alongside with the BF...!

Best regards,

Ladislas

**Comment by richarddmorey** [comment]
Not by default; the effect sizes will depend on the model, and so there's not really any generic way to do it. The two approaches are not really compatible from a UX perspective. But the code is all available on the OSF page, so you can see how they were computed.

**Comment by richarddmorey** [comment]
I'm going to close this up.
