### ISSUE TITLE
strange column names in chains

### ISSUE THREAD

**Issue by richarddmorey** [richarddmorey/BayesFactor#94]
In the recent development version of BayesFactor, the column names when estimating MCMC chains appear to be gibberish. This is likely related to richarddmorey/BayesFactor#91 (@jonathon-love)?

    data(attitude)
    
    ## Compute Bayes factors for all regression models
    output = lmBF(rating ~ complaints, data = attitude, progress=FALSE, posterior = TRUE, iterations = 10000)
    head(output)

Which outputs

    Markov Chain Monte Carlo (MCMC) output:
    Start = 1 
    End = 7 
    Thinning interval = 1 
         .Y29tcGxhaW50cw     sig2          g
    [1,]       0.8992623 98.58542  1.4655239
    [2,]       0.7979037 52.17412  0.4101514
    [3,]       0.8825345 58.63960 15.9017369

(the first column should read "complaints")

**Comment by jonathon-love** [comment]
yeah, my bad. i'll get right on it.

**Comment by jonathon-love** [comment]
i thought your demonstration with a data-set with 'complaints' in it was a bit passive aggressive :P
